[build]
  publish = "dist"
  command = "npm run build"
  [build.environment]
    NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public,max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000,public,immutable"
